# Generated by Django 6.0.5 on 2026-06-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_harveststock'),
        ('core', '0002_harveststock_journalentry_update'),
    ]

    operations = [
    ]
